repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-yaml
          - id: end-of-file-fixer
            exclude_types: [text, svg]
          - id: trailing-whitespace
            exclude_types: [html, text]
    - repo: https://github.com/pycqa/flake8
      rev: 6.1.0
      hooks:
          - id: flake8
            additional_dependencies: [
              flake8-black,
              flake8-docstrings,
              flake8-requirements,
              Flake8-pyproject,
            ]
    - repo: https://github.com/psf/black-pre-commit-mirror
      rev: 23.10.0
      hooks:
          - id: black
            language_version: python3.11

exclude: |
    (?x)(
        ^scripts/|
        ^requirements/
    )
